import glob
from pathlib import Path

# Common replacements across all HTML pages.
common_replacements = [
    ('>About</a>', '>About Us</a>'),
    ('>Departments</a>', '>Categories</a>'),
    ('>Services</a>', '>Products</a>'),
    ('>Doctors</a>', '>Brands</a>'),
    ('>Appointment</a>', '>Order Form</a>'),
    ('>Department Details</a>', '>Category Details</a>'),
    ('>Service Details</a>', '>Product Details</a>'),
    ('<h1 class="sitename">Clinic</h1>', '<h1 class="sitename">SportZone</h1>'),
    ('<span class="sitename">Clinic</span>', '<span class="sitename">SportZone</span>'),
    ('<h1 class="heading-title">About</h1>', '<h1 class="heading-title">About Us</h1>'),
    ('<h1 class="heading-title">Departments</h1>', '<h1 class="heading-title">Categories</h1>'),
    ('<h1 class="heading-title">Services</h1>', '<h1 class="heading-title">Products</h1>'),
    ('<h1 class="heading-title">Service Details</h1>', '<h1 class="heading-title">Product Details</h1>'),
    ('<h1 class="heading-title">Department Details</h1>', '<h1 class="heading-title">Category Details</h1>'),
    ('<h1 class="heading-title">Doctors</h1>', '<h1 class="heading-title">Brands</h1>'),
    ('<h1 class="heading-title">Appointment</h1>', '<h1 class="heading-title">Order Form</h1>'),
    ('<title>404 - Clinic Bootstrap Template</title>', '<title>404 - SportZone</title>'),
    ('<title>About - Clinic Bootstrap Template</title>', '<title>About Us - SportZone</title>'),
    ('<title>Departments - Clinic Bootstrap Template</title>', '<title>Categories - SportZone</title>'),
    ('<title>Services - Clinic Bootstrap Template</title>', '<title>Products - SportZone</title>'),
    ('<title>Doctors - Clinic Bootstrap Template</title>', '<title>Brands - SportZone</title>'),
    ('<title>Appointment - Clinic Bootstrap Template</title>', '<title>Order Form - SportZone</title>'),
    ('<title>Service Details - Clinic Bootstrap Template</title>', '<title>Product Details - SportZone</title>'),
    ('<title>Department Details - Clinic Bootstrap Template</title>', '<title>Category Details - SportZone</title>'),
    ('<title>Contact - Clinic Bootstrap Template</title>', '<title>Contact - SportZone</title>'),
    ('<title>Faq - Clinic Bootstrap Template</title>', '<title>FAQ - SportZone</title>'),
    ('<title>Gallery - Clinic Bootstrap Template</title>', '<title>Gallery - SportZone</title>'),
    ('<title>Privacy - Clinic Bootstrap Template</title>', '<title>Privacy - SportZone</title>'),
    ('<title>Starter Page - Clinic Bootstrap Template</title>', '<title>Starter Page - SportZone</title>'),
    ('<title>Terms - Clinic Bootstrap Template</title>', '<title>Terms - SportZone</title>'),
    ('<title>Testimonials - Clinic Bootstrap Template</title>', '<title>Testimonials - SportZone</title>'),
    ('* Template Name: Clinic', '* Template Name: SportZone'),
    ('* Template URL: https://bootstrapmade.com/clinic-bootstrap-template/', '* Template URL: https://bootstrapmade.com/sportzone-template/'),
    ('contact@example.com', 'sportzone@gmail.com'),
    ('+1 5589 55488 55', '+91 9876543210'),
    ('+1 (555) 987-6543', '+91 9876543210'),
    ('+1 (555) 123-4567', '+91 9876543210'),
    ('info@example.com', 'sportzone@gmail.com'),
    ('hello@designstudio.com', 'sportzone@gmail.com'),
    ('1842 Maple Avenue, Portland, Oregon 97204', 'Chennai, Tamil Nadu, India'),
    ('123 Creative Boulevard, Design District, NY 10012', 'Chennai, Tamil Nadu, India'),
    ('<p class="mb-0">\n                Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo\n                odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum\n                debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat\n                ipsum dolorem.\n              </p>',
     '<p class="mb-0">SportZone is a premium sports equipment store built for athletes and fitness enthusiasts.</p>'),
]

page_replacements = {
    'index.html': [
        ('<div class="badge-item">\n                  <i class="bi bi-shield-check"></i>\n                  <span>Accredited</span>\n                </div>',
         '<div class="badge-item">\n                  <i class="bi bi-trophy"></i>\n                  <span>Premium Gear</span>\n                </div>'),
        ('<div class="badge-item">\n                  <i class="bi bi-clock"></i>\n                  <span>24/7 Emergency</span>\n                </div>',
         '<div class="badge-item">\n                  <i class="bi bi-truck"></i>\n                  <span>Fast Delivery</span>\n                </div>'),
        ('<div class="badge-item">\n                  <i class="bi bi-star-fill"></i>\n                  <span>4.9/5 Rating</span>\n                </div>',
         '<div class="badge-item">\n                  <i class="bi bi-award"></i>\n                  <span>Trusted Brands</span>\n                </div>'),
        ('<h1 data-aos="fade-right" data-aos-delay="300">\n                Excellence in <span class="highlight">Healthcare</span> With Compassionate Care\n              </h1>',
         '<h1 data-aos="fade-right" data-aos-delay="300">\n                Gear Up For Every <span class="highlight">Victory</span>\n              </h1>'),
        ('<p class="hero-description" data-aos="fade-right" data-aos-delay="400">\n                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et\n                dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.\n              </p>',
         '<p class="hero-description" data-aos="fade-right" data-aos-delay="400">\n                Discover premium sports equipment, footwear, apparel, and fitness accessories designed for athletes of all levels.\n              </p>'),
        ('<a href="appointment.html" class="btn btn-primary">Book Appointment</a>',
         '<a href="appointment.html" class="btn btn-primary">Shop Now</a>'),
        ('<a href="https://www.youtube.com/watch?v=Y7f98aduVJ8" class="btn btn-outline glightbox">\n                  <i class="bi bi-play-circle me-2"></i>\n                  Watch Our Story\n                </a>',
         '<a href="https://www.youtube.com/watch?v=Y7f98aduVJ8" class="btn btn-outline glightbox">\n                  <i class="bi bi-shop me-2"></i>\n                  Explore Products\n                </a>'),
        ('<div class="emergency-icon">\n                  <i class="bi bi-telephone-fill"></i>\n                </div>',
         '<div class="emergency-icon">\n                  <i class="bi bi-bag-fill"></i>\n                </div>'),
        ('<small>Emergency Hotline</small>', '<small>Customer Support</small>'),
        ('<strong>+1 (555) 911-2468</strong>', '<strong>+91 9876543210</strong>'),
        ('<h2 class="section-heading">Compassionate Care, Advanced Medicine</h2>',
         '<h2 class="section-heading">Elite Performance Gear for Every Athlete</h2>'),
        ('<p class="lead">For over two decades, we\'ve been dedicated to providing exceptional healthcare that\n                combines cutting-edge medical technology with the personal touch our patients deserve.</p>',
         '<p class="lead">SportZone delivers premium sports equipment, apparel, and accessories with unparalleled quality, performance, and style.</p>'),
        ('<span class="stat-label">Patients Served</span>', '<span class="stat-label">Products Sold</span>'),
        ('<span class="stat-label">Years of Excellence</span>', '<span class="stat-label">Years of Service</span>'),
        ('<span class="stat-label">Medical Specialists</span>', '<span class="stat-label">Trusted Brands</span>'),
    ],
    'about.html': [
        ('<h2>Compassionate Care for Every Family</h2>', '<h2>Sports Gear Designed for Every Champion</h2>'),
        ('<p class="lead">For over two decades, we have been dedicated to providing exceptional healthcare services\n                to our community. Our commitment goes beyond medical treatment—we believe in building lasting\n                relationships with our patients and their families.</p>',
         '<p class="lead">For over two decades, SportZone has been the trusted source for premium sports equipment and performance apparel that athletes depend on.</p>'),
        ('<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et\n                dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip\n                ex ea commodo consequat.</p>',
         '<p>We combine expert product curation, premium supplies, and exceptional service to help fitness enthusiasts and competitive athletes perform at their best.</p>'),
        ('<span class="stat-label">Patients Treated</span>', '<span class="stat-label">Customers Served</span>'),
        ('<span class="stat-label">Years Experience</span>', '<span class="stat-label">Years of Excellence</span>'),
        ('<span class="stat-label">Medical Specialists</span>', '<span class="stat-label">Premium Brands</span>'),
        ('<h4>Compassion</h4>', '<h4>Quality</h4>'),
        ('<p>Providing care with empathy and understanding for every patient\'s unique needs and circumstances.</p>',
         '<p>Delivering premium sporting goods with precision and quality for every athlete.</p>'),
        ('<h4>Excellence</h4>', '<h4>Performance</h4>'),
        ('<p>Maintaining the highest standards of medical care through continuous learning and innovation.</p>',
         '<p>Setting the standard for performance gear with innovative products and expert sourcing.</p>'),
        ('<h4>Integrity</h4>', '<h4>Trust</h4>'),
        ('<p>Building trust through honest communication and ethical practices in all our interactions.</p>',
         '<p>Building customer loyalty through transparent service and reliable product delivery.</p>'),
        ('<h4>Innovation</h4>', '<h4>Innovation</h4>'),
        ('<p>Embracing cutting-edge technology and treatments to improve patient outcomes.</p>',
         '<p>Embracing the latest athletic technology to keep customers ahead of the game.</p>'),
        ('<h3>Accreditations &amp; Certifications</h3>', '<h3>Brands &amp; Partnerships</h3>'),
        ('<p class="section-description">Recognized by leading healthcare organizations for our commitment to\n                quality care</p>',
         '<p class="section-description">Trusted by top sporting brands and athletes for premium product quality and fast fulfillment.</p>'),
    ],
    'services.html': [
        ('<h1 class="heading-title">Services</h1>', '<h1 class="heading-title">Products</h1>'),
        ('<p class="mb-0">\n                Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo\n                odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum\n                debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat\n                ipsum dolorem.\n              </p>',
         '<p class="mb-0">Discover our premium product categories, engineered for athletes and fitness enthusiasts looking for performance-driven sports equipment.</p>'),
        ('<h3>Cardiology</h3>', '<h3>Cricket Bats</h3>'),
        ('<p>Comprehensive heart care with advanced diagnostic tools and treatment options for cardiovascular\n                  conditions.</p>',
         '<p>Precision-crafted bats designed for power, balance, and superior ball control on every pitch.</p>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> ECG Testing</span>',
         '<span class="feature-item"><i class="bi bi-basket3"></i> Premium Willow</span>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> Heart Surgery</span>',
         '<span class="feature-item"><i class="bi bi-shield-check"></i> Pro Level Pick</span>'),
        ('<h3>Neurology</h3>', '<h3>Footballs</h3>'),
        ('<p>Expert neurological care for brain and nervous system disorders with state-of-the-art imaging\n                  technology.</p>',
         '<p>Durable match and training footballs built for excellent flight, grip, and precision on any surface.</p>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> MRI Scans</span>',
         '<span class="feature-item"><i class="bi bi-star"></i> Official Match Grade</span>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> Stroke Care</span>',
         '<span class="feature-item"><i class="bi bi-lightning-charge"></i> Elite Performance</span>'),
        ('<h3>Orthopedics</h3>', '<h3>Running Shoes</h3>'),
        ('<p>Specialized bone and joint treatment including sports medicine and reconstructive surgery procedures.\n                </p>',
         '<p>Lightweight running shoes engineered for comfort, speed, and reliable traction mile after mile.</p>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> Joint Replacement</span>',
         '<span class="feature-item"><i class="bi bi-arrow-up-right"></i> Responsive Cushioning</span>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> Sports Medicine</span>',
         '<span class="feature-item"><i class="bi bi-heart-pulse"></i> Breathable Support</span>'),
        ('<h3>Pediatrics</h3>', '<h3>Gym Equipment</h3>'),
        ('<p>Dedicated healthcare for children from infancy through adolescence with specialized treatment\n                  protocols.</p>',
         '<p>High-quality gym equipment for strength, conditioning, and home workouts built to last.</p>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> Well-Child Visits</span>',
         '<span class="feature-item"><i class="bi bi-bar-chart-line"></i> Durable Construction</span>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> Immunizations</span>',
         '<span class="feature-item"><i class="bi bi-check2-circle"></i> Easy Assembly</span>'),
        ('<h3>Emergency Care</h3>', '<h3>Sports Jerseys</h3>'),
        ('<p>24/7 emergency medical services with rapid response teams and critical care capabilities.</p>',
         '<p>Premium team jerseys and training wear offered in authentic designs for all sports.</p>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> Trauma Center</span>',
         '<span class="feature-item"><i class="bi bi-tshirt"></i> Team Styles</span>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> Critical Care</span>',
         '<span class="feature-item"><i class="bi bi-fire"></i> Performance Fabric</span>'),
        ('<h3>Laboratory Testing</h3>', '<h3>Fitness Accessories</h3>'),
        ('<p>Advanced diagnostic laboratory services with comprehensive testing panels and rapid result delivery.\n                </p>',
         '<p>Essential accessories like gloves, straps, and resistance gear to support every training routine.</p>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> Blood Tests</span>',
         '<span class="feature-item"><i class="bi bi-box-seam"></i> Durable Gear</span>'),
        ('<span class="feature-item"><i class="fas fa-check"></i> Pathology</span>',
         '<span class="feature-item"><i class="bi bi-wrench"></i> Multi-Purpose Use</span>'),
    ],
    'service-details.html': [
        ('<h1 class="heading-title">Service Details</h1>', '<h1 class="heading-title">Product Details</h1>'),
        ('<span>Advanced Neurology</span>', '<span>Premium Cricket Bats</span>'),
        ('<h2>Comprehensive Neurological Care Services</h2>', '<h2>Premium Cricket Bat Collection</h2>'),
        ('<p class="lead">Expert diagnosis and treatment for complex neurological conditions using state-of-the-art\n                technology</p>',
         '<p class="lead">Discover our top-tier cricket bats crafted for power, precision, and professional performance.</p>'),
        ('<h4>Neurological Assessment</h4>', '<h4>Precision Balance</h4>'),
        ('<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium\n                    totam rem aperiam.</p>',
         '<p>Expertly balanced bats built to deliver consistent stroke play and superior control under pressure.</p>'),
        ('<h4>Brain Imaging &amp; Diagnosis</h4>', '<h4>Premium Willow Construction</h4>'),
        ('<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum\n                    deleniti.</p>',
         '<p>Hand-selected willow and reinforced handles provide unmatched durability and swing performance.</p>'),
        ('<h4>Treatment Planning</h4>', '<h4>Custom Bat Fitting</h4>'),
        ('<p>Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim\n                    laborum.</p>',
         '<p>Choose a bat profile that matches your playing style, from aggressive stroke-makers to technical players.</p>'),
        ('<img src="assets/img/health/neurology-2.webp" alt="Neurology Services" class="img-fluid">',
         '<img src="assets/img/health/neurology-2.webp" alt="Premium Cricket Bats" class="img-fluid">'),
        ('<span class="number">95%</span>\n                    <span class="label">Success Rate</span>',
         '<span class="number">95%</span>\n                    <span class="label">Player Satisfaction</span>'),
        ('<span class="number">24/7</span>\n                    <span class="label">Emergency Care</span>',
         '<span class="number">48h</span>\n                    <span class="label">Fast Shipping</span>'),
        ('<h3>Why Choose Our Neurology Department</h3>', '<h3>Why Choose SportZone Gear</h3>'),
        ('<p>Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore\n                    et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut\n                    aliquip ex ea commodo consequat.</p>',
         '<p>Our gear is selected for quality, performance, and value so athletes can train, compete, and recover with confidence.</p>'),
        ('<span>Board Certified Specialists</span>', '<span>Elite Brand Selection</span>'),
        ('<span>Same Day Appointments</span>', '<span>Same Day Shipping</span>'),
        ('<span>Advanced Treatment Options</span>', '<span>Pro-Level Features</span>'),
        ('<span>Patient-Centered Care</span>', '<span>Customer-Driven Service</span>'),
        ('<h4>Conditions We Treat</h4>', '<h4>Product Features</h4>'),
        ('<span class="tag">Stroke Recovery</span>', '<span class="tag">Lightweight Feel</span>'),
        ('<span class="tag">Epilepsy Management</span>', '<span class="tag">High Sweet Spot</span>'),
        ('<span class="tag">Memory Disorders</span>', '<span class="tag">Durable Finish</span>'),
        ('<span class="tag">Headache Disorders</span>', '<span class="tag">Superior Grip</span>'),
        ('<span class="tag">Movement Disorders</span>', '<span class="tag">Fast Swings</span>'),
        ('<span class="tag">Peripheral Neuropathy</span>', '<span class="tag">Balanced Weight</span>'),
        ('<span class="tag">Multiple Sclerosis</span>', '<span class="tag">Power Control</span>'),
        ('<span class="tag">Parkinson\'s Disease</span>', '<span class="tag">Professional Feel</span>'),
        ('<h4>Schedule Consultation</h4>', '<h4>Order Yours Today</h4>'),
        ('<p>Book your neurological evaluation with our expert team</p>', '<p>Reserve your premium bat and get ready for peak performance.</p>'),
        ('<h4>Emergency Consultation</h4>', '<h4>Live Store Support</h4>'),
        ('<p>24/7 neurological emergency support and rapid response</p>', '<p>Expert product advice and support for every purchase.</p>'),
        ('<h4>Get Second Opinion</h4>', '<h4>Request a Personalized Quote</h4>'),
        ('<p>Expert review of existing diagnoses and treatment plans</p>', '<p>Get personalized recommendations from our sports gear specialists.</p>'),
        ('<span class="availability">Next available: Tomorrow</span>', '<span class="availability">Ships within 48 hours</span>'),
        ('<span class="availability">+1 (555) 123-4567</span>', '<span class="availability">+91 9876543210</span>'),
    ],
    'doctors.html': [
        ('<h1 class="heading-title">Doctors</h1>', '<h1 class="heading-title">Brands</h1>'),
        ('<p class="mb-0">\n                Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo\n                odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum\n                debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat\n                ipsum dolorem.\n              </p>',
         '<p class="mb-0">Explore the leading sports brands trusted by athletes around the world for performance, style, and reliability.</p>'),
        ('Dr. Marcus Johnson', 'Nike'),
        ('Cardiologist', 'Performance Footwear & Apparel'),
        ('Dr. Sarah Williams', 'Adidas'),
        ('Neurologist', 'Training Gear & Equipment'),
        ('Dr. Michael Chen', 'Puma'),
        ('Orthopedic Surgeon', 'Sports Lifestyle Essentials'),
        ('Dr. Emily Rodriguez', 'Under Armour'),
        ('Pediatrician', 'Athletic Apparel & Accessories'),
        ('Book Appointment', 'Shop Collection'),
        ('Cardiology Dept.', 'Premium Sports Collection'),
        ('Neurology Dept.', 'Elite Performance Range'),
        ('Orthopedics Dept.', 'Functional Training Gear'),
        ('Pediatrics Dept.', 'Youth Sports Apparel'),
        ('Dermatology Dept.', 'Activewear Essentials'),
        ('Oncology Dept.', 'Signature Sports Brands'),
    ],
    'department-details.html': [
        ('<span class="specialty-badge">Neurology</span>', '<span class="specialty-badge">Cricket Equipment</span>'),
        ('<h1 class="department-title">Advanced Neurological Care</h1>', '<h1 class="department-title">Elite Cricket Equipment</h1>'),
        ('<p class="department-intro">Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere\n                cubilia curae. Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.</p>',
         '<p class="department-intro">Discover our curated cricket collection featuring premium bats, protective gear, and training essentials for serious players.</p>'),
        ('<span class="highlight-text">Emergency Neurology</span>', '<span class="highlight-text">Pro-Grade Bat Selection</span>'),
        ('<span class="highlight-text">Patient Satisfaction</span>', '<span class="highlight-text">Customer Satisfaction</span>'),
        ('<a href="appointment.html" class="btn-primary">Schedule Consultation</a>',
         '<a href="appointment.html" class="btn-primary">Order Now</a>'),
        ('<a href="services.html" class="btn-secondary">\n                  <span>View All Services</span>\n                  <i class="bi bi-arrow-right"></i>\n                </a>',
         '<a href="services.html" class="btn-secondary">\n                  <span>View All Products</span>\n                  <i class="bi bi-arrow-right"></i>\n                </a>'),
        ('<h3>Our Neurological Services</h3>', '<h3>Featured Cricket Gear</h3>'),
        ('<p>Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Mauris blandit aliquet elit, eget\n                  tincidunt nibh pulvinar a.</p>',
         '<p>From premium bats to protective accessories, our cricket gear is engineered to elevate your game.</p>'),
        ('<h4>Epilepsy Treatment</h4>', '<h4>Pro Willow Bats</h4>'),
        ('<p>Nulla porttitor accumsan tincidunt. Cras ultricies ligula sed magna dictum porta.</p>',
         '<p>High-performance willow bats tuned for power and responsiveness.</p>'),
        ('<h4>Diagnostic Imaging</h4>', '<h4>Professional Cricket Balls</h4>'),
        ('<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis.</p>',
         '<p>Match-grade balls designed for consistent seam and swing in every condition.</p>'),
        ('<h4>Stroke Prevention</h4>', '<h4>Protective Gear Sets</h4>'),
        ('<p>Donec sollicitudin molestie malesuada. Proin eget tortor risus cras ultricies ligula.</p>',
         '<p>Pads, gloves, and helmets that deliver confidence and comfort on the field.</p>'),
        ('<h4>Movement Disorders</h4>', '<h4>Training Accessories</h4>'),
        ('<p>Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.</p>',
         '<p>Essential training tools to sharpen technique and increase strength.</p>'),
        ('<h4>Sleep Disorders</h4>', '<h4>Customized Bat Grips</h4>'),
        ('<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod tempor.</p>',
         '<p>Custom grip options for comfort, control, and reduced vibration.</p>'),
        ('<h4>Memory Care</h4>', '<h4>Expert Support</h4>'),
        ('<p>Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a vestibulum ac diam.</p>',
         '<p>Store support that helps you choose the right equipment for your game.</p>'),
        ('<span class="contact-label">Emergency Neurology</span>', '<span class="contact-label">Fast Order Support</span>'),
        ('<span class="contact-text">+1 (555) 234-5678</span>', '<span class="contact-text">+91 9876543210</span>'),
        ('<span class="contact-label">Appointments</span>', '<span class="contact-label">Order Assistance</span>'),
        ('<span class="contact-text">Mon - Fri, 8:00 AM - 6:00 PM</span>', '<span class="contact-text">Mon - Sat, 9:00 AM - 8:00 PM</span>'),
    ],
    'appointment.html': [
        ('<h1 class="heading-title">Appointment</h1>', '<h1 class="heading-title">Order Form</h1>'),
        ('<li class="current">Appointment</li>', '<li class="current">Order Form</li>'),
        ('<h2>Schedule Your Appointment</h2>', '<h2>Place Your Order</h2>'),
        ('<p>Book your medical appointment in just a few simple steps. Our experienced healthcare professionals\n                  are ready to provide you with the best care possible.</p>',
         '<p>Choose your sports gear, quantity, and delivery details, then submit your order for fast fulfillment.</p>'),
        ('<h4>Select Service</h4>', '<h4>Select Product Category</h4>'),
        ('<p>Choose the medical service you need</p>', '<p>Select the category that matches your sport or training needs.</p>'),
        ('<h4>Pick Date &amp; Time</h4>', '<h4>Confirm Quantity</h4>'),
        ('<p>Select your preferred appointment slot</p>', '<p>Choose the number of items you want to order.</p>'),
        ('<h4>Confirm Details</h4>', '<h4>Enter Delivery Details</h4>'),
        ('<p>Provide your information and confirm</p>', '<p>Provide your contact and delivery information.</p>'),
        ('<select name="department" class="form-select" required="">\n                        <option value="">Select Department</option>\n                        <option value="general">General Consultation</option>\n                        <option value="cardiology">Cardiology</option>\n                        <option value="neurology">Neurology</option>\n                        <option value="orthopedics">Orthopedics</option>\n                        <option value="pediatrics">Pediatrics</option>\n                        <option value="dermatology">Dermatology</option>\n                        <option value="oncology">Oncology</option>\n                      </select>',
         '<select name="product-category" class="form-select" required="">\n                        <option value="">Select Product Category</option>\n                        <option value="cricket">Cricket Equipment</option>\n                        <option value="football">Football Gear</option>\n                        <option value="sportswear">Sports Wear</option>\n                        <option value="fitness">Fitness Equipment</option>\n                      </select>'),
        ('<input type="date" name="date" class="form-control" required="">',
         '<input type="number" name="quantity" class="form-control" placeholder="Quantity" min="1" required="">'),
        ('<select name="doctor" class="form-select" required="">\n                        <option value="">Select Doctor</option>\n                        <option value="dr-sarah-johnson">Dr. Sarah Johnson</option>\n                        <option value="dr-michael-chen">Dr. Michael Chen</option>\n                        <option value="dr-emily-davis">Dr. Emily Davis</option>\n                        <option value="dr-robert-smith">Dr. Robert Smith</option>\n                        <option value="dr-lisa-brown">Dr. Lisa Brown</option>\n                        <option value="dr-david-wilson">Dr. David Wilson</option>\n                        <option value="dr-maria-rodriguez">Dr. Maria Rodriguez</option>\n                      </select>',
         '<input type="text" name="delivery" class="form-control" placeholder="Delivery Address" required="">'),
        ('<textarea name="message" class="form-control" rows="4"\n                        placeholder="Additional notes or symptoms (optional)"></textarea>',
         '<textarea name="notes" class="form-control" rows="4"\n                        placeholder="Additional order notes or instructions (optional)"></textarea>'),
        ('<div class="sent-message">Your appointment has been scheduled. Thank you!</div>',
         '<div class="sent-message">Your order has been placed. Thank you!</div>'),
        ('<button type="submit" class="btn-book">Book Appointment Now</button>',
         '<button type="submit" class="btn-book">Place Order Now</button>'),
        ('<p><i class="bi bi-exclamation-triangle"></i> For medical emergencies, please call <strong>911</strong>\n                  or go to the nearest emergency room.</p>',
         '<p><i class="bi bi-truck"></i> Need help with your order? Contact our support team at <strong>+91 9876543210</strong>.</p>'),
    ],
    'faq.html': [
        ('<h1 class="heading-title">Frequenty Asked Questions</h1>', '<h1 class="heading-title">Frequently Asked Questions</h1>'),
        ('<h4>Donec sollicitudin molestie malesuada proin eget tortor?</h4>', '<h4>How long does delivery take?</h4>' ),
        ('<p>Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Donec rutrum congue leo eget\n                      malesuada. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.\n                    </p>',
         '<p>Most orders ship within 24 hours and arrive in 3-5 business days across India depending on your location.</p>'),
        ('<h4>Sed porttitor lectus nibh vivamus magna justo?</h4>', '<h4>Do you offer returns?</h4>'),
        ('<p>Nulla porttitor accumsan tincidunt. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.\n                      Cras ultricies ligula sed magna dictum porta. Vivamus suscipit tortor eget felis porttitor\n                      volutpat.</p>',
         '<p>Yes, we offer a straightforward returns policy within 14 days on most products, subject to condition and packaging.</p>'),
        ('<h4>Pellentesque habitant morbi tristique senectus?</h4>', '<h4>Are products covered under warranty?</h4>'),
        ('<p>Quisque velit nisi, pretium ut lacinia in, elementum id enim. Vestibulum ac diam sit amet quam\n                      vehicula elementum sed sit amet dui. Donec sollicitudin molestie malesuada.</p>',
         '<p>Many items include manufacturer warranties. Specific warranty details are listed on each product page.</p>'),
        ('<h4>Lorem ipsum dolor sit amet consectetur adipiscing?</h4>', '<h4>Do you deliver across India?</h4>'),
        ('<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.\n                      Totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto.</p>',
         '<p>Yes, we deliver across India with reliable shipping partners and localized tracking for your order.</p>'),
        ('<h4>Curabitur aliquet quam id dui posuere blandit?</h4>', '<h4>What payment methods are accepted?</h4>'),
        ('<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum\n                      deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati.</p>',
         '<p>We accept major credit/debit cards, UPI, net banking, and secure digital wallets for a seamless checkout.</p>'),
    ],
    'contact.html': [
        ('<p class="mb-0">\n                Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo\n                odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum\n                debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat\n                ipsum dolorem.\n              </p>',
         '<p class="mb-0">Get in touch with SportZone for premium sports equipment, quick support, and expert shopping assistance.</p>'),
        ('<h3>Our Address</h3>\n                  <p>1842 Maple Avenue, Portland, Oregon 97204</p>',
         '<h3>Our Address</h3>\n                  <p>Chennai, Tamil Nadu, India</p>'),
        ('<h3>Email Address</h3>\n                  <p>info@example.com</p>\n                  <p>contact@example.com</p>',
         '<h3>Email Address</h3>\n                  <p>sportzone@gmail.com</p>'),
        ('<h3>Hours of Operation</h3>\n                  <p>Sunday-Fri: 9 AM - 6 PM</p>\n                  <p>Saturday: 9 AM - 4 PM</p>',
         '<h3>Hours of Operation</h3>\n                  <p>Monday - Saturday: 9 AM - 8 PM</p>\n                  <p>Sunday: 10 AM - 6 PM</p>'),
        ('<iframe\n          src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d48389.78314118045!2d-74.006138!3d40.710059!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a22a3bda30d%3A0xb89d1fe6bc499443!2sDowntown%20Conference%20Center!5e0!3m2!1sen!2sus!4v1676961268712!5m2!1sen!2sus"\n          width="100%" height="500" style="border:0;" allowfullscreen="" loading="lazy"\n          referrerpolicy="no-referrer-when-downgrade"></iframe>',
         '<iframe\n          src="https://maps.google.com/maps?q=Chennai%2C%20India&z=13&output=embed"\n          width="100%" height="500" style="border:0;" allowfullscreen="" loading="lazy"\n          referrerpolicy="no-referrer-when-downgrade"></iframe>'),
        ('<p class="mb-4">Have questions or want to learn more? Reach out to us and our team will get back to you\n                shortly.</p>',
         '<p class="mb-4">Have questions about our products or need help placing an order? Our team is here to help.</p>'),
    ],
    'gallery.html': [
        ('<p class="mb-0">\n                Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo\n                odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum\n                debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat\n                ipsum dolorem.\n              </p>',
         '<p class="mb-0">Browse our sports gallery featuring cricket gear, football equipment, running shoes, and fitness essentials.</p>'),
        ('title="Gallery 1"', 'title="Cricket Bats"'),
        ('title="Gallery 2"', 'title="Footballs"'),
        ('title="Gallery 3"', 'title="Running Shoes"'),
        ('title="Gallery 4"', 'title="Sports Jerseys"'),
        ('title="Gallery 5"', 'title="Training Gear"'),
        ('title="Gallery 6"', 'title="Sports Store Interior"'),
        ('title="Gallery 7"', 'title="Fitness Accessories"'),
        ('title="Gallery 8"', 'title="Athletic Equipment"'),
    ],
    'testimonials.html': [
        ('<p>Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus.\n                  Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.</p>',
         '<p>SportZone delivered the perfect bat for my season; the quality is unbeatable and delivery was super fast.</p>'),
        ('<h4>Marcus Chen <i class="bi bi-patch-check-fill"></i></h4>', '<h4>Sachin Kumar <i class="bi bi-patch-check-fill"></i></h4>'),
        ('<span>@marcuschen</span>', '<span>@sachink</span>'),
        ('<p>Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim\n                  tempor labore quem eram duis noster aute amet eram fore quis sint minim.</p>',
         '<p>Excellent customer support and a wide range of footballs. The quality feels top tier and the fit was perfect.</p>'),
        ('<h4>Sarah Mitchell <i class="bi bi-patch-check-fill"></i></h4>', '<h4>Anita Reddy <i class="bi bi-patch-check-fill"></i></h4>'),
        ('<span>@sarahmitch</span>', '<span>@anitar</span>'),
        ('<p>Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit\n                  minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore.</p>',
         '<p>The running shoes from SportZone are incredibly comfortable and helped me beat my personal best.</p>'),
        ('<h4>James Wilson <i class="bi bi-patch-check-fill"></i></h4>', '<h4>Rohan Verma <i class="bi bi-patch-check-fill"></i></h4>'),
        ('<span>@jwilson</span>', '<span>@rohanv</span>'),
    ],
    '404.html': [
        ('<h1 class="sitename">Clinic</h1>', '<h1 class="sitename">SportZone</h1>'),
    ],
    'privacy.html': [
        ('<h1 class="heading-title">Privacy</h1>', '<h1 class="heading-title">Privacy Policy</h1>'),
        ('<p class="mb-0">\n                Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo\n                odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum\n                debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat\n                ipsum dolorem.\n              </p>',
         '<p class="mb-0">SportZone is committed to protecting your personal information while delivering reliable sports shopping experiences.</p>'),
        ('<p>This Privacy Policy describes how we collect, use, process, and disclose your\n              information, including personal information, in conjunction with your access to and use of our services.\n            </p>',
         '<p>This Privacy Policy describes how SportZone collects, uses, and protects your personal information when you shop with us.</p>'),
    ],
    'terms.html': [
        ('<h1 class="heading-title">Terms</h1>', '<h1 class="heading-title">Terms & Conditions</h1>'),
        ('<p class="mb-0">\n                Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo\n                odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum\n                debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat\n                ipsum dolorem.\n              </p>',
         '<p class="mb-0">Please read SportZone Terms of Service carefully before using our online store or placing an order.</p>'),
        ('<p>By accessing our website and services, you agree to be bound by these Terms of Service and all applicable\n              laws and regulations. If you do not agree with any of these terms, you are prohibited from using or\n              accessing our services.</p>',
         '<p>By accessing SportZone and placing an order, you agree to be bound by these Terms of Service and applicable laws.</p>'),
        ('<p>Our service and its original content, features, and functionality are owned by us and are protected by\n              international copyright, trademark, patent, trade secret, and other intellectual property laws.</p>',
         '<p>SportZone content, design elements, and branded materials are owned by us and protected by copyright, trademark, and other laws.</p>'),
        ('<p>When you create an account with us, you must provide accurate, complete, and current information. Failure\n              to do so constitutes a breach of the Terms, which may result in immediate termination of your account.</p>',
         '<p>When you create a SportZone account, provide accurate and current information. Failure to do so may result in account restrictions.</p>'),
    ],
}

all_files = sorted(glob.glob('*.html'))
for filename in all_files:
    path = Path(filename)
    content = path.read_text(encoding='utf-8')
    original = content
    for old, new in common_replacements:
        content = content.replace(old, new)
    if filename in page_replacements:
        for old, new in page_replacements[filename]:
            content = content.replace(old, new)
    if content != original:
        path.write_text(content, encoding='utf-8')
        print(f'Updated {filename}')
    else:
        print(f'No changes for {filename}')
